worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include        /etc/nginx/mime.types;
    default_type   application/octet-stream;

    sendfile            on;
    keepalive_timeout   65;

    gzip    on;
    gzip_types  text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    #Rate limit por IP
    limit_req_zone $binary_remote_addr zone=api_limit:10m   rate=10r/s;
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;

    #Onde ele procura a aplicacao(porta, dominio), e retorna uma unica url para o navegador
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }  

    #Faz o certificado SSL, usando o protocolo TLS que é o mais utilizado hoje em dia
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/dev/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/dev/priv_key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        root /usr/share/nginx/html;

        #Ele abre na tela do login 
        location / {
            return 302 /html/login.html;
        }

        #Cache-Control no-store significa que o cliente pode guardar uma copia dos dados
        # mas quando utilizado precisa revalidar com o servidor
        location /html/ {
            add_header Cache-Control "no-store";
            try_files $uri =404;
        }

        location /css/ {
            try_files $uri =404;
        }

        location /js/ {
            try_files $uri =404;
        }

        #Aqui tudo que for api é encaminhado pro backend rodando na IDE
        location /api/ {
            proxy_pass http://host.docker.internal:8080/api/;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}